### ISSUE TITLE
Angular 1.3

### ISSUE THREAD

**Issue by solenoo** [danielcrisp/angular-rangeslider#60]
Does it work with Angular 1.3, cause I'm having some issues to implement this in my project.

HTML

```
<div range-slider min="price_min" max="price_max" model-min="price_min_handler" model-max="price_max_handler" disabled="false"></div>
```

JS

```
$scope.prices = [20,30,45,50,52,110,130,200,220];

	$scope.price_min = $scope.prices[0];
	$scope.price_max = $scope.prices[$scope.prices.length - 1];

	$scope.price_min_handler = $scope.price_min;
	$scope.price_max_handler = $scope.price_max;
```

I'm getting no errors yet the slider doesn't work.

**Comment by ZwaarContrast** [comment]
Jup, experiencing this too. The slider appears, but the handles are always on the left and aren't draggable. Also, it doesn't seem to pick up the values. I noticed that a class is supposed to be added when hovering over a handle. It doesn't right now, so I looked at the value of '$slider', and the value of 'handles'. Slider is set, I see an element when I log it, but handles returns an array with two empty objects. I guess the problem is in the "element.find" section on line 172 of angular.rangeSlider.js. Maybe there is another way of accessing template elements in a directive?

**Comment by ZwaarContrast** [comment]
Hah! Looked a bit further and found that jqLite is used by default in AngularJS when jQuery is not present. in jqLite the find() method is limited to lookups by tag name. Including jQuery fixes the problem. Not really an issue in the Rangeslider, merely a dependency issue.

**Comment by mattymess** [comment]
I'm having the same issue, but even when I include jQuery, I can't drag the pointer.

**Comment by danielcrisp** [comment]
Yep unfortunately jQuery is still a dependency.

@mattymess can you provide a fiddle example?

**Comment by mattymess** [comment]
I forgot to reply back that I resolved my issue. The problem was that I was
loading jquery after angular.

Thanks for getting back to me, Daniel.

On Tuesday, March 24, 2015, danielcrisp <notifications@github.com> wrote:

> Yep unfortunately jQuery is still a dependency.
>
> @mattymess <https://github.com/mattymess> can you provide a fiddle
> example?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/danielcrisp/angular-rangeslider/issues/60#issuecomment-85465490>
> .
>


-- 

----
*Matt Messinger*
C: *858 337 9780*
